In [1]:
import numpy as np
import CSF
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib auto
plt.style.available
plt.style.use('seaborn')

Using matplotlib backend: Qt5Agg


## 布料模拟法滤波（漆建波，2016）

In [2]:
csf = CSF.CSF()
csf.readPointsFromFile('test.txt')

In [3]:
csf.params.bSloopSmooth = False
csf.params.cloth_resolution = 0.1

In [4]:
ground = CSF.VecInt()  # a list to indicate the index of ground points after calculation
non_ground = CSF.VecInt() # a list to indicate the index of non-ground points after calculation
csf.do_filtering(ground, non_ground) # do actual filtering.
csf.savePoints(ground,"ground.txt")

In [5]:
data = np.loadtxt('ground.txt')
print(data)

[[-24.04  -24.878  -5.222]
 [-23.789 -24.421  -5.149]
 [-23.467 -24.876  -5.162]
 ...
 [ 24.823  24.856  -1.203]
 [ 24.949  24.386  -1.317]
 [ 24.964  24.5    -0.71 ]]


In [6]:
origin = np.loadtxt('test.txt')# preprocessed data

In [7]:
ax = plt.axes(projection='3d') 

In [8]:
ax.plot(origin[:,0],origin[:,1],origin[:,2],'.',markersize=0.5)
ax.plot(data[:,0],data[:,1],data[:,2],'r.',markersize=0.5)

### 结论
1. 未对离散点进行过滤，对离散点的处理效果较差
2. 处理后有部分非地形点得以保留，需要调整为合适的参数。

## 形态法滤波

使用`text.cpp`在`filter.cpp`中进行测试。